#!/usr/bin/perl

use feature qw( switch );
use warnings;
use GelfPush;
use Config::IniFiles;
use Data::Dumper;
use threads;
use Getopt::Long;

my (@inis_enabled, $graylog2_sever, @watcherThreads, $debug, $config);
my $options = GetOptions(
				"debug" => \$debug,
				"help" => \$help );
				
if( defined($debug) ) {
	print "Debugging is on!\n";
}
if( defined($help) ) {
	print "gelfPush [options]\n";
	print "	--help	Displays this help screen\n";
	print "	--debug	Turns on debugging\n";
	exit(0);
}

sub INT_handler {
	print "Hi There!  Getting a list of threads for you!\n";
	foreach my $thr (threads->list()) {
		print "Thread " . $thr->tid() . " is about to die!\n";
		$thr->kill('KILL')->join();
	}
	exit(-1);
}
sub HUP_handler {
	print "Time to write a restart function!!\n";
}
sub TERM_handler {
	print "Getting ready to kill some threads for you!!\n";
	foreach my $thr (threads->list()) {
		print "Thread " . $thr->tid() . " is about to die!\n";
		$thr->kill('KILL')->join();
	}
	exit(0);
}

$SIG{'INT'} = 'INT_handler';
$SIG{'HUP'} = 'HUP_handler';
$SIG{'TERM'} = 'TERM_handler';

if( $debug ) {
	$config = Config::IniFiles->new( -file => "gelfPush.conf" ) or die("$!\n");
} else {
	$config = Config::IniFiles->new( -file => "/etc/gelfPush.conf" ) or die("$!\n");
}

foreach $block ( $config->Sections() ) {
	if($debug) { print "Section: $block\n"; }
	if( $block ne 'GLOBAL' && $config->val( $block, 'enabled' ) == 1 ) {
		push( @inis_enabled, $block );
	}
}

if( @inis_enabled == 0 ) {
	die("No blocks are enabled\n");
} else {
	print "Inis enabled: " . @inis_enabled . "\n";
	if( $debug ) { print Dumper( @inis_enabled ); }
}
$graylog2_server = $config->val('GLOBAL', 'graylog2_sever') or die("No graylog2_server defined in [GLOBAL]\n");

if($debug) { print "Server: $graylog2_server\n"; }

for my $action (@inis_enabled) {
	print "Action: $action\n";
	my $thr = threads->create( \&spawn_watcher, $graylog2_server, $action );
	push(@watcherThreads, $thr);
}

while(1) { }

sub spawn_watcher {
	### ARGS: Hostname, watcher
	my $hostname = $_[0];
	my $watcher = $_[1];
	
	if($debug) { print "Graylog2 Server: $hostname\n"; }
	
	given($watcher) {
		when("APACHE_LOGGING") {
			if($debug) { print "Apache log watching enabled...\n"; }
			GelfPush::watcher_apache_access($hostname);
		}
		when("SECURE_LOG") {
			if($debug) { print "Secure log watching enabled...\n"; }
			GelfPush::watcher_secure($hostname);
		}
	}
}